image: node:16.14.0

pipelines:
  branches:
    develop:
      - step:
          name: Installation
          caches:
            - node
          script:
            - npm install
          artifacts:
            - node_modules/** # Save modules for next steps
      - step:
          name: Build
          script:
            - npm run build
          artifacts:
            - dist/** # Save build for next steps
      - step:
          name: Deploy to S3
          deployment: production
          script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: eu-central-1
                S3_BUCKET: giodots-password-manager-dev
                LOCAL_PATH: "dist/dpm-frontend-v2"
                ACL: "public-read"